# Title: TSVFormatterForJSApp.R
# Author: Ssurey Moon
#
# Reference: 
#       [1] https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting
#
# Visualizing the result
#  - Target and Prediction plot cross departments
#
# Generate tsv files
#  - Target and predicted data of each store cross departments
#  - Javascript App to show the result (url): https://github.com/SsureyMoon/App-LineChart-SalesForcasting
#
# This uses the data generated by FitSVMforWalmartCrossDept.py
#
# Input file : Under the directory './scikitSVM'
#              result_deptX.txt : predicton on training set and test set for department X
#              result_dept_testX.txt : predicton on training set and test set for department X
#              y_min_max1.csv : minum and maximum value of target data which will be used to denormalize the prediction
#              c_gamma1.tsv : optimal parameters for RBF kernel of SVM(Support Vector Machines)
#
# Output file : Under the directory './visual_data'
#              error_rate_store_dept.tsv : training errors
#              actual_storeXstore_deptY.tsv: 



#rm(list=ls())
setwd(".")
train = read.csv("train.csv", header=TRUE) 
test = read.csv("test.csv", header = TRUE)

library(ggplot2)

err_rate <- list()

#Choose the range of departments to plot
dept_from = 1
dept_to = 99

total_result <- list()
test_result <- list()
currend_wd <- getwd()

filename_for_y_max_y_min = paste(currend_wd, '/y_min_max1.csv', sep="")
y_min_max <- read.csv(filename_for_y_max_y_min, header=TRUE, stringsAsFactors=FALSE)

for(dept in dept_from:dept_to){
  tryCatch({
    filename_for_total_result = paste(currend_wd, '/scikitSVM/result_dept', dept, '.txt', sep="")
    filename_for_test_result = paste(currend_wd, '/scikitSVM/result_dept_test', dept, '.txt', sep="")
    filename_for_y_max_y_min = paste(currend_wd, '/y_min_max1', sep="")
    
    total_result[[dept]] =  as.vector(as.matrix(read.csv(file=filename_for_total_result, header=FALSE)))
    test_result[[dept]] =  as.vector(as.matrix(read.csv(file=filename_for_test_result, header=FALSE)))
    
    total_result[[dept]]  = 10^(total_result[[dept]])+y_min_max$y_min[dept]# *(y_max-y_min) + y_min
    test_result[[dept]]  = 10^(test_result[[dept]])+y_min_max$y_min[dept]# *(y_max-y_min) + y_min
    
    plot(total_result[[dept]], type='n', main=c(sprintf('Weekly sales of departments %d of all stores', dept)))
    lines(total_result[[dept]], col='red')
    lines(train$Weekly_Sales[train$Dept==dept], col='blue')}
    ,
    error = function(c){print(message(c))})
}


bkwd <- getwd()
setwd('./visual_data')
error_rate_on_training_data = data.frame(store=c(1:45))
error_rate_on_training_data = merge(error_rate_on_training_data, data.frame(depart=c(1:99)))
error_rate_on_training_data = merge(error_rate_on_training_data, data.frame(error=c(-1)))

?data.frame
for(dept in dept_from:dept_to){
  for(i in unique(test$Store[test$Dept==dept])){
    train_complete_deptX = train[train$Dept==dept,]
    train_complete_deptX$result <- total_result[[dept]][1:nrow(train[train$Dept==dept,])]


    test_complete_deptX <- test[test$Dept==dept,]
    test_complete_deptX$Weekly_Sales <- test_result[[dept]]
    
    if(i %in% unique(train$Store[train$Dept==dept])){
      plot_points_train <- with(train_complete_deptX, c(min(which(Store == i & Dept == dept)), max(which(Store == i & Dept == dept))))
    }
    
    plot_points_test <- with(test_complete_deptX, c(min(which(Store == i & Dept == dept)), max(which(Store==i & Dept == dept))))
    if(i %in% unique(train$Store[train$Dept==dept])){
      prediction <- c(train_complete_deptX$result[plot_points_train[1]:plot_points_train[2]], test_complete_deptX$Weekly_Sales[plot_points_test[1]:plot_points_test[2]])
      pred_date = c(as.Date(train_complete_deptX$Date[plot_points_train[1]:plot_points_train[2]]), as.Date(test_complete_deptX$Date[plot_points_test[1]:plot_points_test[2]]))
      error_rate_on_training_data$error[error_rate_on_training_data$store==i & error_rate_on_training_data$depart==dept] = sqrt(sum((train_complete_deptX$result[plot_points_train[1]:plot_points_train[2]] - train_complete_deptX$Weekly_Sales[plot_points_train[1]:plot_points_train[2]])^2))/(plot_points_train[2]-plot_points_train[1])
    }
    else
    {
      prediction <- c(test_complete_deptX$Weekly_Sales[plot_points_test[1]:plot_points_test[2]])
      pred_date = test_complete_deptX$Date[plot_points_test[1]:plot_points_test[2]]
    }
    
    plot(prediction, type = 'n', main=c(sprintf("Department %d, Store %d", dept, i)))
    if(i %in% unique(train$Store[train$Dept==dept])){
      line_x = train_complete_deptX$Weekly_Sales[plot_points_train[1]:plot_points_train[2]]
      actual_date = train_complete_deptX$Date[plot_points_train[1]:plot_points_train[2]]
      lines(line_x)
      
      actual_formattedDataFrame <- data.frame(date=actual_date, sales=line_x)
      write.table(actual_formattedDataFrame, file=paste('actual_store', i, 'store_dept', dept, '.tsv', sep =""), sep='\t', col.names=TRUE, row.names=FALSE, quote=FALSE)
    }
    lines(prediction, col='red')

    pred_formattedDataFrame <- data.frame(date=pred_date, sales=prediction)
    write.table(pred_formattedDataFrame, file=paste('pred_store', i, 'store_dept', dept, '.tsv', sep =""), sep='\t', col.names=TRUE, row.names=FALSE, quote=FALSE)
  }
  
}

write.table(error_rate_on_training_data,  row.names=FALSE, file="error_rate_store_dept.tsv", sep='\t')
setwd(bkwd)